CREATE TABLE `security_audit_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_key` varchar(191) NOT NULL,
	`oidc_jti_hash` varchar(64) NOT NULL,
	`outcome` enum('clean','attention','failed') NOT NULL,
	`production_info_count` int NOT NULL DEFAULT 0,
	`production_low_count` int NOT NULL DEFAULT 0,
	`production_moderate_count` int NOT NULL DEFAULT 0,
	`production_high_count` int NOT NULL DEFAULT 0,
	`production_critical_count` int NOT NULL DEFAULT 0,
	`full_info_count` int NOT NULL DEFAULT 0,
	`full_low_count` int NOT NULL DEFAULT 0,
	`full_moderate_count` int NOT NULL DEFAULT 0,
	`full_high_count` int NOT NULL DEFAULT 0,
	`full_critical_count` int NOT NULL DEFAULT 0,
	`production_dependency_count` int NOT NULL DEFAULT 0,
	`full_dependency_count` int NOT NULL DEFAULT 0,
	`updated_package_count` int NOT NULL DEFAULT 0,
	`test_status` enum('passed','failed','not_run') NOT NULL,
	`build_status` enum('passed','failed','not_run') NOT NULL,
	`failure_code` varchar(64),
	`failure_summary` varchar(300),
	`repository` varchar(255) NOT NULL,
	`repository_id` varchar(32) NOT NULL,
	`repository_owner_id` varchar(32) NOT NULL,
	`ref` varchar(255) NOT NULL,
	`event_name` varchar(64) NOT NULL,
	`workflow` varchar(255) NOT NULL,
	`workflow_ref` varchar(512) NOT NULL,
	`workflow_sha` varchar(40) NOT NULL,
	`run_id` varchar(32) NOT NULL,
	`run_number` int NOT NULL,
	`run_attempt` int NOT NULL,
	`run_url` varchar(512) NOT NULL,
	`event_at` bigint NOT NULL,
	`duration_ms` int,
	`received_at` bigint NOT NULL,
	CONSTRAINT `security_audit_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `security_audit_reports_event_key_unique` UNIQUE(`event_key`),
	CONSTRAINT `security_audit_reports_oidc_jti_unique` UNIQUE(`oidc_jti_hash`)
);
--> statement-breakpoint
CREATE INDEX `security_audit_reports_event_idx` ON `security_audit_reports` (`event_at`);--> statement-breakpoint
CREATE INDEX `security_audit_reports_outcome_event_idx` ON `security_audit_reports` (`outcome`,`event_at`);